name: unittest

on:
  workflow_call:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  unittest:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          python3 -m venv .venv
          source .venv/bin/activate
          pip install jsonschema

      - name: Run crucible python unit tests
        run: |
          source .venv/bin/activate
          python3 -m unittest discover -s bin -p "test_*.py" -v
